spring:
  application:
    name: notification-service
  # Kafka Properties
  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.microtest.notificationservice.event.OrderPlacedEvent
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
server:
  port: 0
  error:
    include-message: ALWAYS