server:
  port: 8009
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Video Service Route
        - id: vtube
          uri: lb://vtube
          predicates:
            - Path=/vtube/api/v1/**
        # Discovery Service Route
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Discovery Service Static Resources Route
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/vtube
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:eureka}@localhost:8761/eureka
logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.routeRouteDefinitionLocator: INFO
#JWT CONVERTOR
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: account