spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Video Service Route
        - id: product-service
          uri: lb://video-service
          predicates:
            - Path=/api/product, /api/product/test/**
        # Discovery Service Route
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        # Discovery Service Static Resources Route
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm
eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka
logging:
  level:
    root: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.routeRouteDefinitionLocator: INFO
